[toolchain]
package_manager = "pnpm"
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mention = "5xA4v2SasSoE8mPnWSpePV3U4piHgag51od6mrNDU8j8"

[programs.devnet]
mention = "5xA4v2SasSoE8mPnWSpePV3U4piHgag51od6mrNDU8j8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"