export const SEEDS = [
  {
    id: 1,
    title: "Will they say \u201cAI\u201d?",
    event: "Solana Speedrun #12 — live dev stream",
    vertical: "streams",
    type: "binary",
    b: 1_000_000_000,
    words: [],
    endMin: 25,
    outcome: "yes",
  },
  {
    id: 2,
    title: "First word said: race",
    event: "xAI Grok 5 launch livestream",
    vertical: "streams",
    type: "majority",
    b: 1_000_000,
    words: ["agents", "open source", "benchmark", "Grok", "safety", "physics", "nothingburger"],
    endMin: 40,
    outcome: "agents",
  },
  {
    id: 3,
    title: "Will Powell say \u201cpause\u201d?",
    event: "FOMC press conference",
    vertical: "earnings",
    type: "binary",
    b: 250_000_000,
    words: [],
    endMin: 15,
    outcome: "no",
  },
  {
    id: 4,
    title: "Word race: post-game interview",
    event: "NBA Finals G7 — courtside mic",
    vertical: "sports",
    type: "majority",
    b: 1_000_000,
    words: ["credit the team", "we fought", "MVP", "God bless", "next season"],
    endMin: 30,
    outcome: "MVP",
  },
  {
    id: 5,
    title: "Will he say \u201cW in the chat\u201d?",
    event: "Kai Cenat — subathon stream",
    vertical: "streams",
    type: "binary",
    b: 500_000_000,
    words: [],
    endMin: 20,
    outcome: "yes",
  },
  {
    id: 6,
    title: "Earnings call buzzword race",
    event: "NVDA Q4 earnings call",
    vertical: "earnings",
    type: "majority",
    b: 1_000_000,
    words: ["data center", "AI demand", "guidance", "supply", "sovereign AI"],
    endMin: 45,
    outcome: "data center",
  },
  {
    id: 7,
    title: "Will the mayor say \u201chousing\u201d first minute?",
    event: "NYC mayoral debate",
    vertical: "politics",
    type: "binary",
    b: 1_000_000_000,
    words: [],
    endMin: 12,
    outcome: "yes",
  },
  {
    id: 8,
    title: "Will Lex say \u201csimulation\u201d?",
    event: "Lex Fridman #412 — guest TBA",
    vertical: "podcasts",
    type: "binary",
    b: 600_000_000,
    words: [],
    endMin: 18,
    outcome: "yes",
  },
];

export const END_OFFSETS = { 1: 25, 2: 40, 3: 15, 4: 30, 5: 20, 6: 45, 7: 12, 8: 18 };